### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tuanteku9x** [Ashaxer/MuskEmpire_autobuy#1]
Paste your auth Api-Key:
5c6bb7e0d867d698f31728181e097fc087cff16332375675448fb5e4ee2f4ccb
get_dbs method: False
get_assets method: False
get_all method: False
=======================
Traceback (most recent call last):
  File "C:\Users\tuan-bu\Desktop\MuskEmpire_autobuy-main\main.py", line 159, in <module>
    print("Money:", sync_data["data"]["hero"]["money"]//100000/10,"M")
                    ^^^^^^^^^
NameError: name 'sync_data' is not defined. Did you mean: 'new_sync_data'?

**Comment by Ashaxer** [comment]
The problem is with the MuskEmpire Bot itself, it cannot submit its Api-Key to the game, therefore these requests are not succeeding. Whenever the game loaded in the webapp, then you can use its Api-Key
![image](https://github.com/user-attachments/assets/ef8ee09b-b9f7-40ae-a3d8-09e7f06d0592)

**Comment by lorvent** [comment]
I am also getting same error, can you please find what the issue is?

**Comment by Ashaxer** [comment]
> I am also getting same error, can you please find what the issue is?

This error has been fixed, read the instructions (user-agent)
